server:
  port: ${PORT:8080}

encryption:
  key: thisisa128bitkey

security:
  jwt:
    secret: ThisIsAnExample
    expiration-time: 14000000
    token-prefix: Bearer
    header-prefix: Authorization
    authorities: authorities

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root_test
    password: root_test